### ISSUE TITLE
Move all imagery to a single location

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/.teams#78]
Right now our images are spread all over core.  This is not needed.  Lets move all brand imagery to /img so everything is easy to find.
<img width="527" alt="image" src="https://github.com/Bearsampp/.teams/assets/1850089/5a49a1a5-fc05-4d41-9192-3b81797a1d72">

This will require editing some core code and testing thoroughly.

**Comment by jwaisner** [comment]
Updated in Sandbox.
