### ISSUE TITLE
New xdc source?

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/.teams#83]
the xdc that we've used is long past old & gone.  HOWEVER it looks like xdebug has a version 
that is more current then ours
https://packagecontrol.io/packages/Xdebug%20Client

We should look into upgrading or removing it.

**Comment by jwaisner** [comment]
Here is an actively maintained source: https://github.com/xdebug/xdebug/releases

**Comment by N6REJ** [comment]
looks like https://xdebug.org/docs/dbgpClient is the replacement

**Comment by N6REJ** [comment]
after speaking with the developer of xdebug he said that what we have has more functionality then what else is around so we keep it till it stops working I guess.  He had never heard of ours so I gave him the only link I have.
