### ISSUE TITLE
modal box truncated

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/.teams#92]
Modal window when starting or stopping is truncated
![image](https://github.com/Bearsampp/.teams/assets/1850089/5415566d-9956-4019-ade7-da83efead708)

**Comment by jwaisner** [comment]
it isnt truncated, the "..." is at the end of every statement during boot up or shutdown regardless of how long or short it is.

**Comment by N6REJ** [comment]
no, look how its half height!

**Comment by N6REJ** [comment]
solved in 2024.4.30

**Comment by N6REJ** [comment]
Like a nightmare its back

**Comment by N6REJ** [comment]
fixed in sandbox commit
