### ISSUE TITLE
phppgadmin replacement

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/.teams#99]
> Please follow this guide to file a proper request report : http://bearsampp.com/request

* Name:  pgadmin
* Description:  alternative to phppgadmin
* Website:  https://www.enterprisedb.com/blog/pgadmin-user-management
* License (e.g. Freeware, OSS, GPL, MIT, etc): 
* Comment (anything else which might help): 
Looks like we'd run it in "server mode" so that its a web app

**Comment by jwaisner** [comment]
Done
